application: codeslower
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin/shell.*
  script: handlers/shell/shell.py
  login: admin

- url: .*
  script: main.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 )$